liveblog.settings:
  type: config_object
  label: 'Liveblog settings'
  mapping:
    notification_channel:
      type: string
      label: 'Notification channel'

liveblog.liveblog_post.settings:
  type: config_object
  label: 'Liveblog post settings'
  mapping:
    preview:
      type: boolean
      label: 'Preview'
